on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main, feature ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # Updated to v3

    # Java 8 setup
    - name: Set up JDK 8
      uses: actions/setup-java@v3 # Assuming v3 is available and does not use deprecated features
      with:
        java-version: '8'
        distribution: 'adopt'

    # Building the application with Maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    # Publishing test results
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: target/surefire-reports/*.xml

    # Upload the build artifacts
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3 # Updated to v3 assuming it is available
      with:
        name: my-app-1.0
        path: target/*

    # Setup Docker
    - name: Install Docker
      uses: docker/setup-buildx-action@v2 # Updated to v2
      with:
        install: true
          
    # Docker build
    - name: Docker build
      run: |
        docker build -t my-app:latest .
